typography_spectrum: 0.11671273014508188
color:
  brandStrength: 0.22756377840414643
  lightness: 0.836520409444347
  saturation: 0.47013206826522946
  rhythmicContrast: 0.5530797943938524
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.511205539572984
author:
  name: Xochimilco Ventures
  email: pato@collective.academy
  url: www.about.me/patobichara
name: Xochimilco Ventures
navigation:
  - id: e8757798-48ac-4c2e-9e44-e614476b25ea
    url: 2016-07-18-about-us.html
    name: About us
    type: content
title: Mexico's premier early-stage fund
