typography_spectrum: 0.8644644708838314
color:
  brandStrength: 0.4463763067033142
  lightness: 0.9694118434563279
  saturation: 0.5152890770696104
  rhythmicContrast: 0.6577759787905961
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
layout_spectrum: 0.05496294819749892
author:
  name: Xochimilco Ventures
  email: pato@collective.academy
  url: www.about.me/patobichara
name: Xochimilco Ventures
title: Mexico's premier early-stage fund
